# Generated by Django 2.1.7 on 2019-05-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190520_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='local',
            field=models.CharField(blank=True, max_length=100, verbose_name='local'),
        ),
    ]
