# Generated by Django 2.1.7 on 2019-05-12 12:10

from django.db import migrations, models
import workshop.subscriptions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190512_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='cpf',
            field=models.CharField(max_length=11, validators=[workshop.subscriptions.validators.validate_cpf], verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
    ]
